import type { Metadata } from 'next';
import { Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/shared/header/Header';
import Providers from '@/components/shared/Providers';
import { articulatCF } from '@/fonts/articulat/articulat';

const interFont = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'latin-ext'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Nikica Ražnatović',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${interFont.variable} ${geistMono.variable} ${articulatCF.variable} antialiased`}
      >
        <Providers>
          <div className='mx-auto max-w-screen-md px-4 pt-6 pb-10'>
            <Header />
            <div className='mt-10'>{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
